# Queries that result in a host count within this range will be considered "interesting" and will be marked as such in the results. 
rarity:
    min: 2
    max: 150

# how many hours to cache both host results and search results before we lazil expire them. 
cache_duration: 168h0m0s

# when we have a depth that is greater than zero, we can process the sub-queries in parallel. This defines 
# how many goroutines we start up for this. Three is a good number for not getting blocked by the API.
workers: 3

# These are auxiliary query generators, when all of the entries in the `fields` list are present in the host,
# then the query will be generated that ANDs all of the fields together.
# so, if both tls.ja4s and protocol are present, then the query will be generated as: host.services: (tls.ja4s="..." and protocol="...")
# This can be useful when you have some certificate or something that results in a ton of hosts using just one field, but a limited number of hosts
# when combined with another field.
extraction_rules:
    - fields:
        - tls.ja4s
        - protocol
    - fields:
        - cert.fingerprint_sha256
        - protocol
    - fields:
        - cert.parsed.subject_dn
        - protocol
    - fields:
        - cert.parsed.issuer_dn
        - protocol
    - fields:
        - cert.parsed.issuer.locality
        - cert.parsed.subject.locality
    - fields:
        - cert.parsed.subject_dn
        - cert.parsed.issuer_dn
    - scope: endpoints
      fields:
        - http.protocol
        - http.status_code
        - http.status_reason
    - scope: endpoints
      fields:
        - http.protocol
        - http.status_code
        - http.status_reason
        - http.html_title
    - fields:
        - banner_hash_sha256
        - protocol

# These are filter OUT rules, meaning that if these fields are present, they will be ignored by censeye.
# Any field that ends with a "." is a wildcard, meaning that any field that starts with the prefix will be ignored.
# Note: if you use one of these fields in an `extraction_rules` rule, then that rule will never trigger. 
#       If you want this type of feature, use `filters_re` instead.
filters:
    - host.whois.
    - host.dns.
    - host.location.
    - host.services.threats.
    - host.services.scan_time
    - host.services.transport_protocol
    - host.ip
    - host.services.ja4tscan.scan_time
    - host.service_count
    - host.autonomous_system.
    - host.services.ip
    - host.services.vulns.
    - host.services.endpoints.http.body
    - host.services.banner
    - host.services.endpoints.banner
    - host.services.cert.parsed.validity_period.not_before
    - host.services.cert.parsed.validity_period.not_after
    - host.services.endpoints.scan_time
    - host.services.tls.versions.version
    - host.services.tls.version_selected
    - host.services.software.evidence.literal_match
    - host.services.software.evidence.proprietary
    - host.services.labels.source
    - host.services.jarm.scan_time
    - host.services.cert.zlint.timestamp
    - host.services.jarm.transport_protocol
    - host.services.cert.added_at
    - host.services.software.source
    - host.services.cert.parse_status
    - host.services.cert.modified_at
    - host.services.cert.validated_at
    - host.services.cert.parsed.subject.postal_code
    - host.services.cert.parsed.issuer.postal_code
    - host.services.software.
    - host.services.endpoints.transport_protocol
    - host.operating_system.
    - host.services.cert.zlint.
    - host.services.cert.ct.
    - host.services.cert.validation.
    - host.services.cert.revocation.
    - host.services.labels.
    - host.services.cert.validation_level
    - host.services.cert.parsed.extensions.
    - host.services.endpoints.http.body_hash_sha1
    - host.services.cert.parsed.subject_key_info.
    - host.services.endpoints.http.supported_versions
    - host.services.jarm.port
    - host.services.tls.versions.
    - host.services.jarm.is_success
    - host.services.cert.parsed.signature.valid
    - host.services.port
    - host.services.endpoints.port
    - host.services.cert.parsed.signature.
    - host.services.cert.parent_spki_subject_fingerprint_sha256
    - host.services.jarm.ip
    - host.services.endpoints.hostname
    - host.services.endpoints.endpoint_type
    - host.services.cert.parsed.version
    - host.services.endpoints.ip
    - host.services.ssh.kex_init_message.
    - host.services.ssh.algorithm_selection.client_to_server_alg_group.
    - host.services.ssh.server_host_key.ecdsa_public_key.
    - host.services.endpoints.http.uri
    - host.services.endpoints.http.body_size
    - host.services.operating_systems.
    - host.services.cert.fingerprint_sha1
    - host.services.endpoints.http.favicons.hash_md5
    - host.services.endpoints.http.favicons.hash_shodan
    - host.services.ssh.algorithm_selection.server_to_client_alg_group.
    - host.services.endpoints.http.favicons.size
    - host.services.misconfigs.
    - host.services.dcerpc.endpoints.
    - host.services.endpoints.http.favicons.name
    - host.services.endpoints.http.body_hash_tlsh
    - host.services.hardware.
    - host.services.banner_hex
    - host.services.cert.tbs_no_ct_fingerprint_sha256
    - host.services.cert.tbs_fingerprint_sha256
    - host.services.cert.spki_subject_fingerprint_sha256
    - host.services.cert.spki_fingerprint_sha256
    - host.services.cert.fingerprint_md5
    - host.services.tls.fingerprint_sha256
    - host.services.cert.parsed.serial_number
    - host.services.cert.parsed.serial_number_hex
    - host.services.endpoints.open_directory.files.last_modified
    - host.services.endpoints.open_directory.files.size
    - host.services.endpoints.open_directory.files.extension
    - host.services.endpoints.open_directory.files.suspicious_score
    - host.services.endpoints.open_directory.files.path
    - host.services.endpoints.cobalt_strike.x86.sleep_time
    - host.services.endpoints.cobalt_strike.x64.sleep_time
    - host.services.endpoints.cobalt_strike.x86.cookie_beacon
    - host.services.endpoints.cobalt_strike.x64.cookie_beacon
    - host.services.mysql.connection_id
    - host.services.postgres.protocol_error.
    - host.services.postgres.startup_error.
    - host.services.redis.info_response.
    - host.services.redis.raw_command_output.output
    - host.services.cert.parsed.validity_period.length_seconds
    - host.labels.
    - host.services.portmap.v3_entries.
    - host.services.dns.
    - host.services.l2tp.ordered_messages_raw
    - host.services.telnet.do.
    - host.services.telnet.dont.
    - host.services.telnet.will.
    - host.services.telnet.wont.
    - host.services.smb.negotiation_log.system_time
    - host.services.cert.names
    - host.services.ntp.
    - host.services.pptp.
    - host.services.tls.cipher_selected
    - host.services.mqtt.connection_ack_raw
    - host.services.mysql.
    - host.services.ike.
    - host.services.ssh.algorithm_selection.
    - host.services.exposures.
    - host.services.smb.negotiation_log.
    - host.services.smb.session_setup_log.
    - host.services.rdp.selected_security_protocol.
    - host.services.rdp.x224_cc_pdu_srcref
    - host.services.rdp.version.
    - host.services.rdp.connect_response.
    - host.services.smb.smb_version.major
    - host.services.smb.smb_version.minor
    - host.services.smb.smb_version.revision
    - host.services.winrm.
    - host.services.cert.parsed.issuer.province
    - host.services.cert.parsed.subject.province
    - host.services.cert.parsed.subject.country
    - host.services.cert.parsed.issuer.country
    - host.services.ftp.status_code
    - host.services.ssh.server_host_key.rsa_public_key.
    - host.services.ssh.endpoint_id.protocol_version
    - host.services.ssh.hassh_fingerprint
    - host.hardware.
    - host.services.endpoints.prometheus_target.metric_families.help
    - host.services.jarm.cipher_and_version_fingerprint
    - host.services.endpoints.pprof.
    - host.services.smb.smb_version.version_string
    - host.services.cert.parsed.ja4x
    - host.services.l2tp.sccrp.attribute_values.
    - host.services.endpoints.cobalt_strike.x86.http_post.client
    - host.services.endpoints.cobalt_strike.x86.http_get.client
    - host.services.endpoints.cobalt_strike.x64.http_post.client
    - host.services.endpoints.cobalt_strike.x64.http_get.client
    - host.services.screenshots.

# these are more filter OUT rules, but instead we can define a regex that matches the _enttirety_ of a cenql query.
# So any full cenql query that censeye generates, if it matches one of these, then the query is ignored.
# Many of these are just extremely common queries that are not relevant to us, so we filter them out.
#
# Unlike the `filters` above, this does not affect combined queries. 
re_filters:
    - ^host\.services\.endpoints\.http\.protocol="HTTP/1\.[01]"$
    - ^host\.services\.endpoints\.path="(/|/robots\.txt)"
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="date" and endpoints\.http\.headers\.value="<REDACTED>"\)$
    - ^host\.services:\(endpoints\.http\.headers\.key="Connection" and endpoints\.http\.headers\.value="close"\)$
    - ^host\.services\.endpoints\.http\.status_code="(200|301|302|307|400|401|402|403|404|503)"$
    - ^host\.services\.endpoints\.http\.html_title="404 Not Found"$
    - ^host\.services\.endpoints\.http\.status_reason="Not Found"$
    - ^host\.services:\(endpoints\.http\.protocol="HTTP/1\.[01]" and endpoints\.http\.status_code="404" and endpoints\.http\.status_reason="Not Found"\)$
    - ^host\.services\.endpoints\.http\.html_title="Not Found"$
    - ^host\.services:\(endpoints\.http\.protocol="HTTP/1\.[01]" and endpoints\.http\.status_code="404" and endpoints\.http\.status_reason="Not Found" and endpoints\.http\.html_title="Not Found"\)$
    - ^host\.services\.cert\.parsed\.ja4x="7022c563de38_7022c563de38_e73b053161df"$
    - ^host\.services:\(endpoints\.http\.headers\.key="Server" and endpoints\.http\.headers\.value="Microsoft-HTTPAPI/2.0"\)$
    - ^host\.services\.endpoints\.http\.html_tags="<META HTTP-EQUIV=\\\"Content-Type\\\" Content=\\\"text/html; charset=us-ascii\\\">"$
    - ^host\.services:\(endpoints\.http\.headers\.key="Content-Type" and endpoints\.http\.headers\.value="text/html; charset=us-ascii"\)$
    - ^host\.services\.jarm\.tls_extensions_sha256="fd9c9d14e4f4f67f94f0359f8b28f532"$
    - ^host\.services\.endpoints\.http\.html_tags="<TITLE>Not Found</TITLE>"$
    - ^host\.services\.endpoints\.http\.body_hash_sha256="ce7127c38e30e92a021ed2bd09287713c6a923db9ffdb43f126e8965d777fbf0"$
    - ^host\.services\.ja4tscan\.fingerprint="8192_2-1-3-4-8_1460_8_3-6"$
    - ^host\.services\.endpoints\.banner_hash_sha256="d7de42c1e8c09cf951e3ad6248fda3ab48a60ca3eac8b25effd4b3067df8f362"$
    - ^host\.services\.banner_hash_sha256="d7de42c1e8c09cf951e3ad6248fda3ab48a60ca3eac8b25effd4b3067df8f362"$
    - ^host\.services\.endpoints\.http\.html_title="IIS Windows Server"$
    - ^host\.services\.cert\.parsed\.issuer\.organization="DigiCert Inc"$
    - ^host\.services\.jarm\.fingerprint="26d26d16d26d26d22c26d26d26d26dfd9c9d14e4f4f67f94f0359f8b28f532"$
    - ^host\.services\.protocol="[^"]+"$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Content-Length" and endpoints\.http\.headers\.value="[^"]+"\)$
    - cert\.parsed\.(subject_dn|issuer_dn)[:=]"C=AU, ST=Some-State, O=Internet Widgits Pty Ltd"
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Content-Type" and endpoints\.http\.headers\.value="text/plain"\)$
    - tls\.ja3s="(303951d4c50efb2e991652225a6f02b1|15af977ce25de452b96affa2addb1036|f75082535b4a79c07b31bdd0e2b7eb87|475c9302dc42b2751db9edcac3b74891)"
    - tls\.ja4s="(t120200_c02f_344b4dce5a52|t130200_1302_a56c5b993250|t120100_009d_bc98f8e001b5|t130200_1303_a56c5b993250)"
    - ^host\.services\.ssh\.endpoint_id\.software_version="OpenSSH_7\.4"$
    - ^host\.services\.ssh\.endpoint_id\.software_version="OpenSSH_8\.7"$
    - ^host\.services\.banner_hash_sha256="be0da7ee170f9a69bc13b9e61ecfc9110c27db40f3f2e4c0ffae6741f064af8a"$
    - ^host\.services\.banner_hash_sha256="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"$
    - ^host\.services\.banner_hash_sha256="45555cb663eaed691ee601ea9829a3ecb09f649e9f580f69eccc85986a831c90"$
    - ^host\.services\.cert\.parsed\.(issuer|subject)\.organization="Internet Widgits Pty Ltd"$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Content-Type" and endpoints\.http\.headers\.value="text/html"\)$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Connection" and endpoints\.http\.headers\.value="keep-alive"\)$
    - ^host\.services:\(endpoints\.http\.headers\.key="Server" and endpoints\.http\.headers\.value="nginx"\)$
    - ^host\.services\.endpoints\.http\.html_tags="<title>404 Not Found</title>"$
    - ^host\.services:\(endpoints\.http\.protocol="HTTP/1\.[01]" and endpoints\.http\.status_code="404" and endpoints\.http\.status_reason="Not Found" and endpoints\.http\.html_title="404 Not Found"\)$
    - ^host\.services\.endpoints\.http\.status_reason="OK"$
    - ^host\.services:\(endpoints\.http\.protocol="HTTP/1\.[01]" and endpoints\.http\.status_code="200" and endpoints\.http\.status_reason="OK"\)$
    - ^host\.services:\(endpoints\.http\.headers\.key="Transfer-Encoding" and endpoints\.http\.headers\.value="chunked"\)$
    - ^host\.services:\(endpoints\.http\.headers\.key="X-Content-Type-Options" and endpoints\.http\.headers\.value="nosniff"\)$
    - ^host\.services:\(endpoints\.http\.headers\.key="Accept-Ranges" and endpoints\.http\.headers\.value="bytes"\)$
    - ^host\.services:\(endpoints\.http\.headers\.key="Content-Type" and endpoints\.http\.headers\.value="text/html; charset=utf-8"\)$
    - ^host\.services\.endpoints\.http\.status_reason="Moved Permanently"$
    - ^host\.services:\(endpoints\.http\.protocol="[^"]+" and endpoints\.http\.status_code="301" and endpoints\.http\.status_reason="Moved Permanently"\)$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Content-Type" and endpoints\.http\.headers\.value="text/plain; charset=utf-8"\)$
    - ^host\.services\.endpoints\.http\.body_hash_sha256="b16e15764b8bc06c5c3f9f19bc8b99fa48e7894aa5a6ccdad65da49bbf564793"$
    - ^host\.services\.endpoints\.banner_hash_sha256="d01d33874c1a1716026081b3b3fc90b8173203aba832874a8faf5e56e0058837"$
    - ^host\.services\.banner_hash_sha256="d01d33874c1a1716026081b3b3fc90b8173203aba832874a8faf5e56e0058837"$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Keep-Alive" and endpoints\.http\.headers\.value="timeout=5"\)$
    - ^host\.services\.endpoints\.http\.html_tags="<meta charset=utf-8>"$
    - ^host\.services\.endpoints\.http\.status_reason="NOT FOUND"$
    - ^host\.services\.endpoints\.http\.status_reason="Service Unavailable"$
    - ^host\.services:\(endpoints\.http\.headers\.key="Server" and endpoints\.http\.headers\.value="Apache"\)$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="X-Frame-Options" and endpoints\.http\.headers\.value="SAMEORIGIN"\)$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Content-Encoding" and endpoints\.http\.headers\.value="gzip"\)$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Pragma" and endpoints\.http\.headers\.value="no-cache"\)$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="X-XSS-Protection" and endpoints\.http\.headers\.value="1; mode=block"\)$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Vary" and endpoints\.http\.headers\.value="Accept-Encoding"\)$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="Content-Type" and endpoints\.http\.headers\.value="text/html; charset=UTF-8"\)$
    - ^host\.services\.cert\.parsed\.issuer\.organization="Let's Encrypt"$
    - ^host\.services\.tls\.presented_chain\.issuer_dn="C=US, O=Internet Security Research Group, CN=ISRG Root X1"$
    - ^host\.services\.endpoints\.http\.html_tags="<meta charset=\\\"utf-8\\\">"$
    - ^host\.services\.endpoints\.http\.status_reason="Found"$
    - ^host\.services:\(endpoints\.http\.protocol="HTTP/1\.1" and endpoints\.http\.status_code="302" and endpoints\.http\.status_reason="Found"\)$
    - ^host\.services\.endpoints\.http\.html_title=""$
    - ^host\.services\.ftp\.status_meaning="Service ready for new user\."$
    - ^host\.services\.endpoints\.http\.html_tags="<meta charset=\\\"UTF-8\\\">"$
    - \.(presented_chain|tls|parsed)\.(subject|issuer)_dn="C=US, O=DigiCert Inc, OU=www\.digicert\.com, CN=DigiCert Global Root (G2|CA)"$
    - ^host\.services\.ssh\.endpoint_id\.raw="SSH-2\.0-OpenSSH_7\.4"$
    - ^host\.services\.endpoints\.http\.html_tags="<meta name=\\\"viewport\\\" content=\\\"width=device-width, initial-scale=1\.0\\\">"$
    - parsed\.issuer\.organizational_unit="www\.digicert\.com"$
    - ^host\.services\.endpoints\.http\.html_tags="<meta charset=\\\"utf-8\\\"/>"$
    - ^host\.services:\(endpoints\.http\.headers\.key="Referrer-Policy" and endpoints\.http\.headers\.value="strict-origin-when-cross-origin"\)$
    - ^host\.services:\(endpoints\.http\.headers\.key="X-Permitted-Cross-Domain-Policies" and endpoints\.http\.headers\.value="none"\)$
    - ^host\.services\.endpoints\.http\.status_reason="Temporary Redirect"$
    - ^host\.services:\(endpoints\.http\.protocol="HTTP/1\.1" and endpoints\.http\.status_code="307" and endpoints\.http\.status_reason="Temporary Redirect"\)$
    - ^host\.services\.cert\.parsed\.issuer_dn="C=US, O=DigiCert Inc, OU=www\.digicert\.com, CN=RapidSSL TLS RSA CA G1"$
    - ^host\.services:\(endpoints\.http\.headers\.key="X-Download-Options" and endpoints\.http\.headers\.value="noopen"\)$
    - (?i)^host\.services:\(endpoints\.http\.headers\.key="(Last-Modified|Expires|X-Runtime)" and endpoints\.http\.headers\.value="[^"]+"\)$
    - ^host\.services\.endpoints\.open_directory\.files\.name="[^"]{1,7}\.[^"]+"$
